config/routes.rb
SecureWarehouse::Application.routes.draw do
  get "units/new"
  get "units/create"
  get "units/destroy"
  get "units_controller/new"
  get "units_controller/create"
  get "units_controller/destroy"
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :units, only: [:new, :create, :destroy, :index]
  root 'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  

  

end

app/models/unit.rb
class Unit < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 2000 }
  validates :category, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :units, dependent: :destroy
  before_save { self.login = login.downcase }
  before_create :create_remember_token
  
  validates :login, presence: true, length: { maximum: 30 }, uniqueness: { case_sensitive: false }
  validates :first_name, presence: true, length: { maximum: 50 }
  validates :second_name, presence: true, length: { maximum: 50 }
  
  has_secure_password
  validates :password, length: { minimum: 6 }
  
  def new_remember_token
    #SecureRandom.urlsafe_base64
	Digest::SHA2.hexdigest(self.login + Time.now.to_s + SecureRandom.random_number(100).to_s)
  end
  
  def User.encrypt(token)
    Digest::SHA2.hexdigest(token.to_s)
  end
  
  private
    def create_remember_token
	  self.remember_token = User.encrypt(new_remember_token)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(login: params[:session][:login].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
	  redirect_to root_url
    else
      flash.now[:error] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end
  
  def destroy
    sign_out
	redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy  

  def initialize
    @categories = ['Weapon', 'Survival gear', 'Clothes', 'Surveillance', 'Medicament', 'Computing equipment', 'Spare parts', 'Other']
    
    super
  end
  
  def categories_select
    select = []
	(1..@categories.length).to_a.each { |i| select.push([@categories[i-1], i]) }  
    select
  end
  
  def new
    @unit = Unit.new
  end

  def create
    @unit = current_user.units.build(unit_params)
    if @unit.save
      flash[:success] = "Unit is stored!"
      redirect_to units_path
    else
      render 'new'
    end
  end

  def destroy
    @unit.destroy
	redirect_to units_path
  end
  
  def index
    @query = params[:q]
	@search_in = params[:filter_content]
	@commit = params[:commit]
	@only_categories = params[:filter_category]
	if @only_categories == nil
		@only_categories = []
	end
	if @query != '' and @commit == 'find'
	  part_by_title = "title like '%#{@query}%'"
	  part_by_description = "description like '%#{@query}%'"
	  whole_query = ''
	  
	  category_part = ''
	  only_categories_strings = []
	  @only_categories.each do |i|
	    category_number = i.to_i
	    if category_number >= 1 and category_number <= 8
	      only_categories_strings.push "category=#{i}"
		end
	  end
	  category_part = only_categories_strings.join(' or ')
	  if category_part != ''
	    category_part = '(' + category_part + ') and '
	  end
	  
	  if @search_in == 'in_title'
	    whole_query = "#{category_part}#{part_by_title}"
	  elsif @search_in == 'in_description'
	    whole_query = "#{category_part}#{part_by_description}"
	  elsif @search_in == 'in_both'
	    whole_query = "#{category_part}#{part_by_title} or #{part_by_description}"
	  end
	  
	  if whole_query != ''
	    @units = current_user.units.where(whole_query).paginate(page: params[:page])
	  else
	    @units = current_user.units.paginate(page: params[:page])
	  end
	else
	  @units = current_user.units.paginate(page: params[:page])
    end
  end
  
  private
    def unit_params
      params.require(:unit).permit(:title, :description, :category, :shared)
    end

    def correct_user
      @unit = current_user.units.find_by(id: params[:id])
      redirect_to root_url if @unit.nil?
    end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update]
  before_action :correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
  end
  
  def index
    @users = User.paginate(page: params[:page])
  end
  
  def new
	@user = User.new
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
	if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
	else
	  render 'edit'
	end
  end
  
  def create
    @user = User.new(user_params)
	if @user.save
	  sign_in @user
	  flash[:success] = "Welcome to the SecureWarehouse!"
	  redirect_to @user
	else
	  render 'new'
	end
  end
  
  private
    def user_params
	  params.require(:user).permit(:login, :first_name, :second_name, :password, :password_confirmation)
	end
	
	def correct_user
	  @user = User.find(params[:id])
	  redirect_to(root_url) unless current_user?(@user)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "SecureWarehouse"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end  
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = user.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end  
  
  def signed_in?
    !current_user.nil?
  end
  
  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end
  
  def current_user?(user)
    current_user == user
  end
  
  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
  
  def signed_in_user
    unless signed_in?
	  store_location
	  redirect_to signin_url, notice: "Please sign in"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
  <section>
    <span>SecureWarehouse service</span>
	<span>by SenTieL</span>
  </section>
  <section>
    <%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>
  </section>
  <section>
    <%= link_to image_tag("logo.png", alt: "VolgaCTF"), 'http://volgactf.ru' %>
  </section>
  <section>
    <span><%= link_to 'VolgaCTF', 'http://volgactf.ru' %> 2013 Final</span>
    <span>Samara, September 5</span>
	<span><%= link_to 'Koibasta', 'http://koibasta.ru' %></span>
  </section>

  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
	<div class="container">
	  <%= link_to "SecureWarehouse", root_path, id: "logo" %>
	  <nav>
		<ul class="nav pull-right">
		  <li><%= link_to "Home", root_path %></li>
          <% if signed_in? %>
            <li id="some-menu" class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
				Units <b class="caret"></b>
				</a>
				<ul class="dropdown-menu">
					<li><%= link_to "View", units_path %></li>
					<li class="divider"></li>
					<li><%= link_to "Add new unit", new_unit_path %></li>
				</ul>
			</li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user.login %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>		  
		</ul>
	  </nav>
	</div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
	<%= render 'layouts/header' %>
    <div class="container">
	  <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
	<%= render 'layouts/footer' %>
	<%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_user_info.html.erb
<h1>
  <%= "#{current_user.first_name} #{current_user.second_name} (#{current_user.login})" %>
</h1>

<%= link_to content_tag(:i, nil, class: 'icon-wrench icon-white') + ' settings', edit_user_path(current_user), {class: 'btn btn-danger'} %>

<h3>
  <%= pluralize(current_user.units.count, "unit") %>
</h3>
<%= link_to content_tag(:i, nil, class: 'icon-align-justify icon-white') + ' view units', units_path, {class: 'btn btn-info'} %>
<%= link_to content_tag(:i, nil, class: 'icon-plus icon-white') + ' store unit', new_unit_path, {class: 'btn btn-primary'} %>

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
    </aside>
  </div>
<% else %>
  <div class="center hero-unit">
    <div id="myCarousel" class="carousel slide">
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
		<li data-target="#myCarousel" data-slide-to="2"></li>
		<li data-target="#myCarousel" data-slide-to="3"></li>
	  </ol>
      <!-- Carousel items -->
      <div class="carousel-inner">
        <div class="active item"><%= link_to image_tag("carousel/handle.png", alt: "Handle") %></div>
        <div class="item"><%= link_to image_tag("carousel/fork2.png", alt: "Fork2") %></div>
		<div class="item"><%= link_to image_tag("carousel/palet.png", alt: "Palet") %></div>
		<div class="item"><%= link_to image_tag("carousel/fork5.png", alt: "Fork5") %></div>
      </div>
    </div>    
    
	<section id="homeSection">
    <h1>Welcome to the SecureWarehouse</h1>
    <h2>
      This is the place where you can store your units securely.
    </h2>

    <%= link_to "Sign up now!", signup_path,
                                class: "btn btn-large btn-primary" %>	
	</section>
	<div class="clearfix"></div>
  </div>
  
<% end %>

app/views/units/_unit.html.erb
<li>
  <div>
  <h4><%= unit.title %></h4>
  <span class="label label-inverse category"><%= @categories[unit.category-1] %></span>  
  </div>
  <p class="description"><%= unit.description %></p>
  <span class="timestamp">
    Began to store <%= time_ago_in_words(unit.created_at) %> ago.
  </span>
  <%= link_to_if current_user?(unit.user), content_tag(:i, nil, class: 'icon-remove icon-white') + ' remove', unit, method: :delete, data: { confirm: "Are you sure?" }, title: unit.title, class: 'btn btn-danger btn-small' %>  
  
</li>

app/views/units/create.html.erb
<h1>Units#create</h1>
<p>Find me in app/views/units/create.html.erb</p>

app/views/units/destroy.html.erb
<h1>Units#destroy</h1>
<p>Find me in app/views/units/destroy.html.erb</p>

app/views/units/index.html.erb
  <div class="span10">
    <% if current_user.units.any? %>
      <h3>Units (<%= current_user.units.count %>)</h3>
	  <div>
		<%= form_tag('#', method: "get", class: 'form-inline') do %>
		  <%= text_field_tag :q, @query, class: 'span6 search-query' %>
		  <%= button_tag(type: 'submit', class: 'btn btn-success', name: 'commit', value: 'find') do %>
			<i class="icon-white icon-search"></i> find
		  <% end %>
		  <br />
		  <%= radio_button_tag :filter_content, 'in_title', @search_in == 'in_title', class: 'inline' %>
		  <%= label_tag :filter_content_in_title, 'In title', class: 'inline' %>
		  <%= radio_button_tag :filter_content, 'in_description', @search_in == 'in_description', class: 'inline' %>
		  <%= label_tag :filter_content_in_description, 'In description', class: 'inline' %>
		  <%= radio_button_tag :filter_content, 'in_both', @search_in == 'in_both', class: 'inline' %>
		  <%= label_tag :filter_content_in_title, 'In both', class: 'inline' %>
		  <br />	
		  <%= label_tag :filter_category, 'Filter by category' %>
		  <br />
		  <%= select_tag :filter_category, options_for_select(controller.categories_select, @only_categories), {:multiple => true, :size => 8, :class => 'span6'} %>
			
		  
		<% end %>
	  </div>
      
	  <%= link_to content_tag(:i, nil, class: 'icon-plus icon-white') + ' store unit', new_unit_path, {class: 'btn btn-primary'} %>
	  
	  <ol class="units">
        <%= render @units %>
      </ol>
      <%= will_paginate @units %>
    <% end %>
  </div>

app/views/units/new.html.erb
<% provide(:title, 'Store unit') %>
<h1>Store unit</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@unit) do |f| %>
	  <%= render 'shared/error_messages', object: f.object %>
	
      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :description %>
      <%= f.text_field :description %>

	  <%= f.label :category %>
	  <%= f.select :category, controller.categories_select %>
	  
      <%= f.submit "Store unit", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/_user.html.erb
<li>
  <%= link_to user.login, user %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :first_name %>
      <%= f.text_field :first_name %>

      <%= f.label :second_name %>
      <%= f.text_field :second_name %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
	
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
	  <%= render 'shared/error_messages', object: f.object %>
	
      <%= f.label :login %>
      <%= f.text_field :login %>

      <%= f.label :first_name %>
      <%= f.text_field :first_name %>

      <%= f.label :second_name %>
      <%= f.text_field :second_name %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.login) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= @user.login %>
      </h1>
    </section>
  </aside>  
</div>